server:
  port: 8080
spring:
  profiles:
    active: dev

  datasource:
    url: ${danifood.datasource.url}
    username: ${danifood.datasource.username}
    password: ${danifood.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

dani:
  jwt:
    secret-key: dani-food-secret-key-2026-abcdefghijklmn
    ttl: 7200000
    employee-token-name: employee_token